config/routes.rb
Rails.application.routes.draw do
  # App routes
  resources :users
  root to: 'home#home', via: :get
  get 'auth/facebook', as: "auth_provider"
  # get 'auth/facebook/callback', to: 'users#login'

  resources :marks 
  resources :cleans
  get 'login' => 'sessions#login'
  get 'dashboard' => 'home#dashboard'
  
  get 'about'=>'home#about'

  resources "contacts", only: [:new, :create]
  get 'contact'=>'contacts#new'

  # OmniAuth Routes
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  # end

  get 'home' => 'home#home'
end

app/models/clean.rb
# == Schema Information
#
# Table name: cleans
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  message    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  aphoto     :string
#  bphoto     :string
#  location   :string
#

class Clean < ActiveRecord::Base
  belongs_to :user
  belongs_to :mark

  mount_uploader :aphoto, PhotoUploader
  mount_uploader :bphoto, PhotoUploader
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Swachh Bharath",
      :to => "anvesh.v@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/mark.rb
# == Schema Information
#
# Table name: marks
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  location   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  photo      :string
#  message    :text
#

class Mark < ActiveRecord::Base
  belongs_to :user
  has_one :clean

  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def current_user_graph(current_user)
      @graph = Koala::Facebook::API.new(current_user)
    end
    helper_method :current_user
    helper_method :current_user_graph
end

app/controllers/cleans_controller.rb
class CleansController < ApplicationController

  def index
    @cleans = Clean.all
    @clean = Clean.new
  end

  # def new
  #   @clean = Clean.new
  # end


  def create
    @clean = Clean.new(clean_params)
    @clean.user_id = current_user.id
    @clean.remote_bphoto_url = @clean.mark.photo_url

    
    if @clean.save
      # redirect_to dashboard_path
    end
    
  end

  def destroy
    @clean = Clean.find(params[:id])
    if(@clean.delete)
      # flash.notice = "Clean id:#{@clean.id}|user_id:#{@clean.user_id}|location:#{@clean.location} deleted!"
      redirect_to dashboard_path
    end
  end

  def show
    @clean = Clean.find(params[:id])
  end

  def update
    @clean = Clean.find(params[:id])
    @clean.isclean = true
    @clean.update_attributes(clean_params)
    redirect_to dashboard_path
  end

  private
  def clean_params
    params.require(:clean).permit(:user_id, :aphoto, :bphoto, :message, :mark_id, :isclean)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def dashboard
  	@marks = Mark.all
    @mark = Mark.new
    # @mark = Mark.new(user_id: current_user.id)
    # @mark = current_user.marks.new

    @cleans = Clean.all
    @clean = Clean.new
  end

  def contact
  end

  def about
    @user = current_user
  end

end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  def index
    @marks = Mark.all
    @mark = Mark.new
  end

  # def new
  #   @mark = Mark.new
  # end

  def create
    @mark = Mark.new(mark_params)
    @mark.user_id = current_user.id
    if @mark.save
      flash.notice = "Mark id:#{@mark.id}|user_id:#{@mark.user_id}|location:#{@mark.location} saved"
      redirect_to dashboard_path
    end
  end

  def show
    @mark = Mark.find(params[:id])
  end

  def destroy
    @mark = Mark.find(params[:id])
    if(@mark.delete)
      flash.notice = "Mark id:#{@mark.id}|user_id:#{@mark.user_id}|location:#{@mark.location} deleted!"
      redirect_to dashboard_path
    end
  end

  def edit
    @mark = Mark.find(params[:id])
  end

  def update
    @mark = Mark.find(params[:id])
    if(@mark.update(mark_params))
      flash.notice = "Mark id:#{@mark.id}|user_id:#{@mark.user_id}|location:#{@mark.location} edit!"
      redirect_to mark_path(@mark)
    end
  end

  private
  def mark_params
    params.require(:mark).permit(:user_id, :location, :photo, :message)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cleans_helper.rb
module CleansHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/cleans/create.js.erb
$("a[href='#join']").tab('show');

app/views/cleans/index.html.erb
<h1>All Cleans</h1>

<%= form_for @clean do |f| %>
  <%= f.text_field :user_id, placeholder: "User ID" %><br>
  <%= f.text_field :location, placeholder: "Location" %><br>
  <%= f.text_field :message, placeholder: "Tell your experience..." %><br>
  <%= f.file_field :bphoto %><br>
  <%= f.file_field :aphoto %><br>
  <%= f.submit %>
<% end %>

<% @cleans.each do |clean| %>
	<div>
		<%= clean.id %> | 
		<%= clean.user_id %> | 
		<%= clean.location %>  
		<%= image_tag clean.bphoto.url, class: "image" %>
		<%= image_tag clean.aphoto.url, class: "image" %>
		<%= link_to "Delete", clean_path(clean), method: :delete %> 
	</div>
<% end %>

app/views/cleans/show.html.erb
<%= @clean.id %>
<%= @clean.location %>
<%= image_tag @clean.aphoto.url %>
<%= image_tag @clean.bphoto.url %>
<%= @clean.message %>

app/views/common/_footer.html.erb
<!-- Footer -->
<footer class="footer">
  <div class="container">
    <p>
    	&copy;
    	Team Five Stars @ Code Astra | 
    	<%= link_to("About Us", about_path) %> | 
    	<%= link_to("Contact Us", contact_path) %>
    </p>
  </div>
</footer>
<!-- End of Footer -->

app/views/common/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-leaf") + " Swachh", dashboard_path, class: "navbar-brand" %>
      <!-- <a class="navbar-brand" href=""><span class="glyphicon glyphicon-leaf"></span> Swach</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user">&nbsp;</span><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Profile</a></li>
            <!-- <li class="divider"></li> -->
            <li><%= link_to "Logout", signout_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- End of Navbar -->

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<%= render 'common/header' %>

<div align="center">
  <h3 class="conhead">Send A message to Us</h3>

  <div> We will be glad to have your feedback and suggestions</div>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

<%= render 'common/footer' %>

app/views/home/_challenge.html.erb
<section role="tabpanel" class="tab-pane" id="challenge">
<h1> Challenge your friends </h1>
<% @cleans.reverse_each do |post| %>
<% if post.isclean %>
  <hr>
  <div class="post"> 
    <%= current_user.name %>
    <span class="post_location"> &nbsp;&nbsp;<%= post.mark.location %> </span>
    <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-trash"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to content_tag(:button, 'Challenge', class: "btn btn-default btn-xs"),post, method: :delete, data: { confirm: 'Are you sure?' } %>
    
  </div>

  <br />

  <div class="post_content">
    <div> 
    	<%= image_tag post.bphoto.url, class: "post_bimage" %>
    	<%= image_tag post.aphoto.url, class: "post_aimage" %>
    </div>
    <div class="post_message"><%= post.message %></div>
  </div>
  <% else %><% end %>
  <% end %>
</section>

app/views/home/_join.html.erb
<section role="tabpanel" class="tab-pane" id="join">
  <h1> Join your friends </h1>
  <% @cleans.reverse_each do |post| %>
  <% if !post.isclean %>
  <hr>
  <div class="post"> 
    <%= post.user.name %>
    <span class="post_location"> &nbsp;&nbsp;<%= post.mark.location %> </span>
    <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-trash"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to content_tag(:button, 'Join', class: "btn btn-default btn-xs"), "#" %>
  </div>

  <br />

  <div class="post_content">
    <div> <%= image_tag post.bphoto.url, class: "post_image" %> </div>
    <div class="post_message"><%= post.mark.message %></div>
    <br />

    <%= simple_form_for post, remote: true, class: "form-horizontal" do |f| %>
    <div class="input_grp container-fluid">
      <div class="icon_container col-xs-1">
        <span class="glyphicon glyphicon-camera"></span>
      </div>
      <div class="col-xs-11">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xs-6"><%= f.input :aphoto, label: "Upload picture" %></div>
          </div>
        </div>
      </div>
    </div>
    <div class="input_grp container-fluid">
      <div class="icon_container col-xs-1">
        <span class="glyphicon glyphicon-comment"></span>
      </div>
      <div class="col-xs-11">
        <%= f.input :message, placeholder: "Description", label: false %>
      </div>
    </div>
    <%= token_tag form_authenticity_token %>
    <%= f.submit "Finish cleaning", class: "btn btn-primary btn-lg", id: "btn-finish" %>
    <% end %>
  </div>
  <% end %>
  <% end %>
</section>

app/views/home/_mark.html.erb
<% unless @mark.photo_url.nil? %><%= image_tag @mark.photo_url %><br />
<%= image_tag @user.avatar_url(:display) %><% end %>
<section role="tabpanel" class="tab-pane active" id="mark">

  <h1>
    Mark a location
  </h1>
  <%= simple_form_for @mark, class: "form-horizontal main-form" do |f| %>
    <div class="input_grp container-fluid">
      <div class="icon_container col-xs-1">
        <span class="glyphicon glyphicon-camera"></span>
      </div>
      <div class="col-xs-11">
        <%= f.input :photo, label: "Upload a picture of dirty place" %>
      </div>
    </div>
    <div class="input_grp container-fluid">
      <div class="icon_container col-xs-1">
        <span class="glyphicon glyphicon-map-marker"></span>
      </div>
      <div class="col-xs-11">
        <%= f.input :location, placeholder: "Area/Place, City", label: false %>
      </div>
    </div>
    <div class="input_grp container-fluid">
      <div class="icon_container col-xs-1">
        <span class="glyphicon glyphicon-comment"></span>
      </div>
      <div class="col-xs-11">
        <%= f.input :message, placeholder: "Description", label: false %>
      </div>
    </div>
    <%= f.hidden_field :user_id %>
    <%= f.submit "Upload", class: "btn btn-primary btn-lg" %>
  <% end %>


  <% @marks.reverse_each do |post| %>
  	<hr>
  	<div class="post">
      <%= post.user.name %>
      <span class="post_location"> &nbsp;&nbsp;<%= post.location %></span>

        <!-- Share on facebook code -->
        <% href = 'http://swachbharat.herokuapp.com/marks/' + post.id.to_s %>
        <% href = Rack::Utils.escape(href) %>
        <% href = "https://www.facebook.com/sharer/sharer.php?u=" + href + "&t=Cleaning%20" %>
        <% href = href + post.location %>
        <a href= "<%= href %>"><%= image_tag 'http://simplesharingbuttons.com/images/simple_icons_black/Facebook.png', width: '26px' %></a>
        <!-- Share on facebook code end -->

        <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-trash"),post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <br />

    <div class="post_content">
      <div> <%= image_tag post.photo.url, class: "post_image" %> </div>
      <div class="post_message"><%= post.message %></div>
      <%= simple_form_for @clean, remote: true, class: "form-horizontal sub-form" do |f| %>
          <%= f.input :mark_id, as: :hidden, input_html: { value: post.id } %>
          <%= f.submit 'Start Cleaning', class: "btn btn-default btn-lg", id: "btn-start" %>
        <% end %>
    </div>
  <% end %>
</section>

app/views/home/about.html.erb
<% if current_user %>
  <%= render 'common/header' %>
<% end %>
    <div class="container" id="about_us">
      <h1>About Us</h1>

      <div id="members">
        <div class="member row">
          <div class="col-xs-3">
            <%= image_tag 'team/anvesh.png' %>
          </div>
          <div class="col-xs-3">
            <h2><span class= "glyphicon glyphicon-star"></span>Anvesh</h2>
            
          </div>
      
        
          <div class="col-xs-3">
            <%= image_tag 'team/rajan.png' %>
          </div>
          <div class="col-xs-3">
            <h2><span class= "glyphicon glyphicon-star"></span>Rajan</h2>
          </div>
        </div>
        
        <div class="member row">
          <div class="col-xs-3">
            <%= image_tag 'team/sri.jpg' %>
          </div>
          <div class="col-xs-3">
            <h2><span class= "glyphicon glyphicon-star"></span>Srikavya</h2>
          </div>
        
          <div class="col-xs-3">
            <%= image_tag 'team/bhavya.jpeg' %>
          </div>
          <div class="col-xs-3">
            <h2><span class= "glyphicon glyphicon-star"></span>Bhavya</h2>

          </div>
        </div>

        <div class="member row">
          <div class="col-xs-4"></div>
          <div class="col-xs-3">
            <%= image_tag 'team/chirag.png' %>
          </div>
          <div class="col-xs-3">
            <h2><span class=" glyphicon glyphicon-star"></span>Chirag</h2>
          </div>
          <div class="col-xs-3"></div>
        </div>
      </div>
    </div>

<%= render 'common/footer' %>

app/views/home/dashboard.html.erb
<% if current_user.nil? %>
<script type="text/javascript">
window.location.href="/home"
</script>
<% else %>
  <%= render partial: "common/header" %>
  <!-- Main Content -->
  <div class="container">
    <div id="main-content" class="col-xs-6 col-xs-offset-3">
      <div role="tabpanel">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#mark" aria-controls="home" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-map-marker"></span>
              &nbsp;Mark
            </a>
          </li>
          <li role="presentation">
            <a href="#join" aria-controls="profile" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-link"></span>
              &nbsp;Join
            </a>
          </li>

          <li role="presentation">
            <a href="#challenge" aria-controls="messages" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-thumbs-up"></span>
              &nbsp;Challenge
            </a>
          </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <%= render partial: "home/mark" %>
          <%= render partial: "home/join" %>
          <%= render partial: "home/challenge" %> 
        </div>
      </div>
    </div>
  </div>
  <!-- End of Main Content -->
  <%= render partial: "common/footer" %>
<% end %>

app/views/home/home.html.erb
<% if current_user %>
  <script type="text/javascript">
    window.location.href="/dashboard"
  </script>
 <% else %>
<div id="bg"></div>

<div class="container-fluid" id="home">
	<div id="scroll-menu">
		<ul>
			<li><a class="smooth_scroll" href="#home">Home</a></li>
			<li><a class="smooth_scroll" href="#mark">Mark</a></li>
			<li><a class="smooth_scroll" href="#clean">Join</a></li>
			<li><a class="smooth_scroll" href="#challenge">Challenge</a></li>
		</ul>
	</div>
	<div id="brand-name">Swachh</div>
	<div id="btn-div">
		<%= link_to "Do your bit", '/auth/facebook', class: "btn btn-success btn-custom" %>
	</div>
</div>

<div class="container-fluid color2" id="mark">
	<div class="feature white">Mark</div>
	<div class="featuretag white">post a pic of the place that needs to be cleaned</div>
</div>

<div class="container-fluid" id="clean">
	<div class="feature white">Join</div>
	<div class="featuretag white">pick a place | invite your friends | make it swachh together</div>
</div>

<div class="container-fluid color1" id="challenge">
	<div class="feature white">Challenge</div>
	<div class="featuretag white">challenge your friends | make the world a better place</div>
</div>
<div id="footer" class="container">
	<div class="container">
		<p class="text-muted">
			&copy;&nbsp;With <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
			 by Team Five Stars | 
	    	<%= link_to("About Us", about_path) %> | 
	    	<%= link_to("Contact Us", contact_path) %>
    	</p>
	</div>
</div>

<% end %>

app/views/home/sample.html.erb
<div class="container-fluid bg">
	<%= image_tag("http://res.cloudinary.com/fivestars/image/upload/v1418495829/taj_low_lawxcf.png", class: "bg-image") %>
</div>

<div class="container-fluid" id="home">
	<div id="scroll-menu">
		<ul>
			<li><a class="smooth_scroll" href="#home">Home</a></li>
			<li><a class="smooth_scroll" href="#mark">Mark</a></li>
			<li><a class="smooth_scroll" href="#clean">Clean</a></li>
			<li><a class="smooth_scroll" href="#challenge">Challenge</a></li>
		</ul>
	</div>
	<div id="brand-name">Swach</div>
	<div id="btn-div">
		<%= link_to "Do your bit", '/auth/facebook', class: "btn btn-success btn-custom" %>
	</div>
</div>

<div class="container-fluid color2" id="mark">
	<div class="feature white">Mark</div>
	<div class="featuretag white">post a pic of the place that needs to be cleaned</div>
</div>

<div class="container-fluid" id="clean">
	<div class="feature white">Clean</div>
	<div class="featuretag white">pick a place | clean it | share your work | encourage others</div>
</div>

<div class="container-fluid color1" id="challenge">
	<div class="feature white">Challenge</div>
	<div class="featuretag white">challenge your friends | make the world a better place</div>
</div>
<div id="footer" class="container">
	<div class="container">
		<p class="text-muted">&copy; Team Five Stars</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Swachh</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<% current_user %>
<%= yield %>

</body>
</html>

app/views/marks/create.js.erb
$("a[href='#challenge']").tab('show');

app/views/marks/index.html.erb
<% if current_user.nil? %>
  <script type="text/javascript">
    window.location.href="/home"
  </script>
<% else %>
<h1>All Marks</h1>

<%= form_for @mark do |f| %>
  <%= f.text_field :user_id, placeholder: "User ID" %>
  <%= f.text_field :location, placeholder: "Location" %>
  <%= f.file_field :photo %>
  <%= f.submit %>
<% end %>

<% @marks.each do |mark| %>
	<div> <%= mark.id %> | <%= mark.user_id %> | <%= mark.location %> <%= image_tag mark.photo.url, class: "image" %> <%= link_to("delete", mark_path(mark) ,method: :delete) %> </div>
<% end %>
<% end %>

app/views/marks/show.html.erb
<%= @mark.id %>
<%= @mark.location %>
<%= image_tag @mark.photo.url %>
<%= @mark.message %>